title: "Takaya UENO - Mathematics Articles"
description: "Exploring the beauty of math in an approachable way."
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

exclude:
  - README.md
